title: Programmering i S-matte
author: Torodd F. Ottestad
copyright: "2022"

repository:
  url: https://github.com/lektorodd/S-matte
  branch: main 
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath

#execute:
#  execute_notebooks: force

# logo.... programmer
# <a href="https://www.flaticon.com/free-icons/programmer" title="programmer icons">Programmer icons created by juicy_fish - Flaticon</a>